// QUE CONTENEDOR SE USA A PARTIR DE UNA VARIABLE DE ENTORNO -- PERSISTENCIA / TIPO DE PERSISTENCIA 
// SI ES JSON SE CARGA LA DEL ARCHIVO, SI ES MEMORIA CARGA LA DE MEMORIA, SI ES MONGO CARGA LA DE MONGO, SI ES FIREBASE CARGA LA DE FIREBASE
// DEVUELVE UN OBJETO DE INSTANCIA PARA PRODUCTO Y UN OBJETO DE INSTANCIA PARA EL CARRITO

